#- name: instal_configure_vsftpd
  #pb installs and configures FTP service on box. user creation and FTPS inclued.
#  hosts: aws_personal
#  remote_user: ec2-user
#  vars: 

#vars was there - moved to right roles folder

#  tasks:

- name: vsftpd-install
    # sudo yum -y install vsftpd
  yum:
    name: vsftpd
    state: latest
  become: yes

- name: vsftpd-configure 1 - create ceritificate
    # sudo mkdir -p /etc/ssl/private
  shell: mkdir -p /etc/ssl/private || openssl req -x509 -nodes -days 730 -newkey rsa:2048 -keyout /etc/ssl/private/vsftpd.pem -out /etc/ssl/private/vsftpd.pem -subj "/C=cc/ST=Default/L=Default/O=Default/CN=carla.grtools.cc"
  args:
    creates: /etc/ssl/private
  become: yes

- name: vsftpd-configure 2 - create ceritificate
    # sudo openssl req -x509 -nodes -days 730 -newkey rsa:2048 -keyout /etc/ssl/private/vsftpd.pem -out /etc/ssl/private/vsftpd.pem
  shell: >
    openssl req -x509 -nodes -days 730 -newkey rsa:2048 
    -keyout /etc/ssl/private/vsftpd.pem 
    -out /etc/ssl/private/vsftpd.pem 
    -subj "/C=cc/ST=Default/L=Default/O=Default/CN=carla.grtools.cc"
  args:
    creates: /etc/ssl/private/vsftpd.pem
  become: yes

- name: vsftpd-configure 3 - copy VSFTPD config file
    # sudo vi /etc/vsftpd/vsftpd.conf
  copy:
#      src: "{{ ansible_prj_location }}/files/vsftpd.conf"
    src: vsftpd.conf
    dest: /etc/vsftpd/vsftpd.conf
    backup: yes
  become: yes

- name: vsftpd-configure 4 - set FTP passive IP address
    # sudo cat /etc/vsftpd/vsftpd.conf | grep 'pasv_address'
  lineinfile:
    path: /etc/vsftpd/vsftpd.conf
    regexp: '^pasv_address='
    line: 'pasv_address={{ elastic_IP }}'
  become: yes

- name: vsftpd-user-creation 1 - create user
    # sudo useradd -d /mnt/$bucket_name -s /sbin/nologin ftpuser1
    # sudo passwd ftpuser1
  user:
    name: ftpuser1
    password: "{{ ftpuser1_password }}"
    state: present
    shell: /sbin/nologin
    system: no
    createhome: no
    home: "/mnt/{{ bucket_name }}"
  become: yes

- name: vsftpd-user-creation 2 - add user to ftp userlist
    # sudo vi /etc/vsftpd.userlist
  copy:
#      src: "{{ ansible_prj_location }}/files/vsftpd.userlist"
    src: vsftpd.userlist
    dest: /etc/vsftpd.userlist
    backup: yes
  become: yes
  notify: "restart vsftpd"

#  handlers:
#  - name: restart-vsftpd
    # sudo systemctl restart vsftpd
    # sudo systemctl enable vsftpd
#    listen: "restart vsftpd"
#    service:
#      name: vsftpd.service
#      state: reloaded
#    enabled: yes