ansible [playbook design]

#case 1:
#ec2_server exist, on eip 
#s3 exist(no_dots_in_name)
#role attached-'ec2 fullaccess to s3'
#ec2 security group inbound ports opened: 990/tcp, 15390:15690/tcp

- name: S3 based FTP server on AWS EC2
  hosts: aws_personal
  remote_user: ec2-user
  vars: 
    ansible_prj_location: /home/sam/proj/gstuff/ansible_personal
    bucket_name: s3fs-001-grtools-cc
    elastic_IP: 18.197.127.113
    ftpuser1_password: $1$1$HEMqaGuDRYFM.lgMogxdf.
    #pwd - anastasy
    #openssl passwd -salt <salt> -1 <password> givesh hash
  tasks:

  - name: yum-update-all
    yum:
      name: '*'
      state: latest
    become: yes

  - name: s3-fuse-install
    yum:
      name: git automake make gcc libstdc++-devel gcc-c++ fuse fuse-devel libcurl-devel curl-devel libxml2-devel mailcap openssl-devel
      state: latest
    shell: mkdir /tmp/misc
    git:
      repo: https://github.com/s3fs-fuse/s3fs-fuse.git
      dest: /tmp/misc
      clone: yes
    shell: autogen.sh || configure
      chdir: /tmp/misc/s3fs-fuse/
    make:
      chdir: /tmp/misc/s3fs-fuse/
      target: install
    become: yes

  - name: s3-mount
    shell: mkdir /mnt/{{ bucket_name }}
    copy:
      src: {{ ansible_prj_location }}/files/fuse.conf
      dest: /etc/fuse.conf
      backup: yes
    shell: /usr/local/bin/s3fs {{ bucket_name }} /mnt/{{ bucket_name }} -o iam_role -o allow_other
    become: yes

  - name: s3-fstab
    mount:
      backup: yes
      path: {{ bucket_name }}
      src: /mnt/{{ bucket_name }}
      fstype: fuse.s3fs
      opts: _netdev,allow_other,iam_role
      state: present
    become: yes

  - name: vsftpd-install
    yum:
      name: vsftpd
      state: latest
    become: yes

  - name: vsftpd-configure
    shell: mkdir -p /etc/ssl/private
    shell: openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/vsftpd.pem -out /etc/ssl/private/vsftpd.pem
    copy:
      src: "{{ ansible_prj_location }}/files/vsftpd.conf"
      dest: /etc/vsftpd/vsftpd.conf
      backup: yes
    become: yes

  - name: vsftpd-user
    user:
      name: ftpuser1
      password: "{{ ftpuser1_password }}"
      state: present
      shell: /sbin/nologin
      system: no
      createhome: no
      home: "/mnt/{{ bucket_name }}"
    copy:
      src: "{{ ansible_prj_location }}/files/vsftpd.userlist"
      dest: /etc/vsftpd.userlist
      backup: yes
    become: yes
    notify: "restart vsftpd"

  handlers:
  - name: restart-vsftpd
    listen: "restart vsftpd"
    service:
      name: vsftpd
      state: reloaded
      enabled: yes